version: '3.4'

services:
  api:
    image: ${REGISTRY}/${API_IMAGE}:${TAG}
    container_name: courses-api
    restart: always
    ports:
      - 8000:8000
    logging:
      driver: syslog
      options:
        tag: "api-production"
    environment:
      - MONGO_URI
      - MONGO_USER
      - MONGO_PASS
      - PASSWORD_SALT
      - JWT_SIGNING_KEY
      - SENDPULSE_LISTID
      - SENDPULSE_ID
      - SENDPULSE_SECRET
      - HTTP_HOST
      - FONDY_MERCHANT_ID
      - FONDY_MERCHANT_PASS
      - PAYMENT_CALLBACK_URL
      - PAYMENT_REDIRECT_URL
      - FRONTEND_URL
      - SMTP_PASSWORD
      - STORAGE_ENDPOINT
      - STORAGE_BUCKET
      - STORAGE_ACCESS_KEY
      - STORAGE_SECRET_KEY
      - APP_ENV
      - CLOUDFLARE_API_KEY
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_ZONE_EMAIL
      - CLOUDFLARE_CNAME_TARGET

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE}:${TAG}
    container_name: courses-api-proxy
    restart: always
    volumes:
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    environment:
      - API_HOST=courses-api
      - API_PORT=8000
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - api