http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 3600s

mongo:
  databaseName: coursePlatform

fileStorage:
  url: ams3.digitaloceanspaces.com
  bucket: courses

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 43200m #30 days

