http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

mongo:
  databaseName: coursePlatform

fileStorage:
  url: ams3.digitaloceanspaces.com
  bucket: courses

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
  verificationCodeLength: 8

limiter:
  rps: 10
  burst: 20
  ttl: 10m

# todo: smtp settings should be configurable for each school individually
smtp:
  host: "mail.privateemail.com"
  port: 587
  from: "no-reply@creatly.me"

email:
  templates:
    verification_email: "./templates/verification_email.html"
    purchase_successful: "./templates/purchase_successful.html"
  subjects:
    verification_email: "Спасибо за регистрацию, %s!"
    purchase_successful: "Покупка прошла успешно!"