http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

mongo:
  databaseName: coursePlatform

fileStorage:
  url: ams3.digitaloceanspaces.com
  bucket: courses

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 43200m #30 days
  verificationCodeLength: 8

limiter:
  rps: 10
  burst: 20
  ttl: 10m

cors:
  allow_origins: [ "http://localhost", "http://localhost:1337", "http://104.236.31.192", "http://104.236.31.192:8000", "http://104.236.31.192:1337" ]

smtp:
  host: "mail.privateemail.com"
  port: 587
  from: "maksim@zhashkevych.com"

email:
  templates:
    verification_email: "./templates/verification_email.html"
    purchase_successful: "./templates/purchase_successful.html"
  subjects:
    verification_email: "Спасибо за регистрацию, %s!"
    purchase_successful: "Покупка прошла успешно!"