http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

mongo:
  databaseName: coursePlatform

fileStorage:
  url: ams3.digitaloceanspaces.com
  bucket: courses

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 43200m #30 days
  verificationCodeLength: 8

limiter:
  rps: 10
  burst: 20
  ttl: 10m

cors:
  allow_origins: ["http://localhost", "http://localhost:1337", "http://104.236.31.192", "http://104.236.31.192:8000", "http://104.236.31.192:1337"]