basePath: /api/v1/
definitions:
  domain.Course:
    properties:
      code:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      name:
        type: string
      published:
        type: boolean
      updatedAt:
        type: string
    type: object
  domain.Lesson:
    properties:
      content:
        type: string
      id:
        type: string
      name:
        type: string
      position:
        type: integer
      published:
        type: boolean
    type: object
  domain.Promocode:
    properties:
      code:
        type: string
      discountPercentage:
        type: integer
      expiresAt:
        type: string
      id:
        type: string
      offerIds:
        items:
          type: string
        type: array
    type: object
  v1.adminUpdateCourseInput:
    properties:
      code:
        type: string
      description:
        type: string
      name:
        type: string
      published:
        type: boolean
    type: object
  v1.createCourseInput:
    properties:
      name:
        type: string
    type: object
  v1.createOrderInput:
    properties:
      offerId:
        type: string
      promoId:
        type: string
    required:
    - offerId
    type: object
  v1.createOrderResponse:
    properties:
      paymentLink:
        type: string
    type: object
  v1.refreshInput:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  v1.response:
    properties:
      message:
        type: string
    type: object
  v1.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  v1.studentGetModuleLessonsResponse:
    properties:
      lessons:
        items:
          $ref: '#/definitions/domain.Lesson'
        type: array
    type: object
  v1.studentSignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      registerSource:
        type: string
    required:
    - email
    - name
    - password
    - registerSource
    type: object
  v1.tokenResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for Course Platform
  title: Course Platform API
  version: "1.0"
paths:
  /admins/auth/refresh:
    post:
      consumes:
      - application/json
      description: admin refresh tokens
      parameters:
      - description: refresh info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.refreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Admin Refresh Tokens
      tags:
      - admins
  /admins/courses:
    get:
      consumes:
      - application/json
      description: admin get all courses
      operationId: adminGetAllCourses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Course'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - AdminAuth: []
      summary: Admin Get All Courses
      tags:
      - admins
    post:
      consumes:
      - application/json
      description: admin create new course
      operationId: adminCreateCourse
      parameters:
      - description: course info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.createCourseInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Course'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - AdminAuth: []
      summary: Admin Create New Courses
      tags:
      - admins
  /admins/courses/{id}:
    get:
      consumes:
      - application/json
      description: admin get course by id
      operationId: adminGetCourseById
      parameters:
      - description: course id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - AdminAuth: []
      summary: Admin Get Course By ID
      tags:
      - admins
    put:
      consumes:
      - application/json
      description: admin update course
      operationId: adminUpdateCourse
      parameters:
      - description: course id
        in: path
        name: id
        required: true
        type: string
      - description: course update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.adminUpdateCourseInput'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - AdminAuth: []
      summary: Admin Update Course
      tags:
      - admins
  /admins/sign-in:
    post:
      consumes:
      - application/json
      description: admin sign in
      operationId: adminSignIn
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Admin SignIn
      tags:
      - admins
  /students/auth/refresh:
    post:
      consumes:
      - application/json
      description: student refresh tokens
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.refreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student Refresh Tokens
      tags:
      - students
  /students/courses:
    get:
      consumes:
      - application/json
      description: student get all courses
      operationId: studentGetAllCourses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Course'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student Get All Courses
      tags:
      - students
  /students/courses/{id}:
    get:
      consumes:
      - application/json
      description: student get course by id
      operationId: studentGetCourseById
      parameters:
      - description: course id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student Get Course By ID
      tags:
      - students
  /students/modules/{id}/lessons:
    get:
      consumes:
      - application/json
      description: student get lessons by module id
      operationId: studentGetModuleLessons
      parameters:
      - description: module id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.studentGetModuleLessonsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - StudentsAuth: []
      summary: Student Get Lessons By Module ID
      tags:
      - students
  /students/modules/{id}/offers:
    get:
      consumes:
      - application/json
      description: student get offers by module id
      operationId: studentGetModuleOffers
      parameters:
      - description: module id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - StudentsAuth: []
      summary: Student Get Offers By Module ID
      tags:
      - students
  /students/order:
    post:
      consumes:
      - application/json
      description: student create order
      operationId: studentCreateOrder
      parameters:
      - description: order info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.createOrderInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.createOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - StudentsAuth: []
      summary: Student CreateOrder
      tags:
      - students
  /students/promocodes/{code}:
    get:
      consumes:
      - application/json
      description: student get promocode by code
      operationId: studentGetPromocode
      parameters:
      - description: code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Promocode'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - StudentsAuth: []
      summary: Student Get Promocode By Code
      tags:
      - students
  /students/sign-in:
    post:
      consumes:
      - application/json
      description: student sign in
      operationId: studentSignIn
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student SignIn
      tags:
      - students
  /students/sign-up:
    post:
      consumes:
      - application/json
      description: create student account
      operationId: studentSignUp
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.studentSignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student SignUp
      tags:
      - students
  /students/verify/{code}:
    post:
      consumes:
      - application/json
      description: student verify registration
      operationId: studentVerify
      parameters:
      - description: verification code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Student Verify Registration
      tags:
      - students
securityDefinitions:
  AdminAuth:
    in: header
    name: Authorization
    type: apiKey
  StudentsAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
